language: ruby
before_install:
  - 'export DISPLAY=:99.0'
  - 'sh -e /etc/init.d/xvfb start'
before_script:
  - cp config/database.yml.travis config/database.yml
  - cp config/smtp.yml.example config/smtp.yml
  - psql -c 'create database "training-benchmarks_test";' -U postgres
